### PR TITLE
Update DEVELOP.md

### PR DESCRIPTION
**Pull request by ihodes**
Add info about daemonizing SauceConnect

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/773)

### CODE REVIEW

**Comment by danvk** [comment]
Please include the bit about `--wait`, too. You may want to verify with @jaclynperrone that this did actually speed up the update-screenshots command (if it did, we're not seeing any evidence of it).

**Comment by ihodes** [comment]
The --wait flag is seltest specific. I'd rather point to the docs then re-document seltest here. (Additionally, interactive is more useful than wait). 




I'd be surprised if this isn't speeding the script up. Will take a look at it on her machine.

**Comment by jaclynperrone** [comment]
@ihodes That would be super helpful! It's taken about 5 minutes to generate the first 8 screenshots.

**Comment by danvk** [comment]
Mentioning that `--wait` and `sel interactive` are useful & linking off to the docs would be really helpful. Neither Jaclyn nor I knew to try those.

**Comment by ihodes** [comment]
I'll add some notes + pointers, makes sense. 

FTR, the slowness appears to be the tunnel between sauce and our office is slow today; we observed this on the SauceLabs videos (pages just taking a long time to load), and saw that the tests when connecting to Travis is much faster.

**Comment by ihodes** [comment]
@dan back to you (I left out --wait as mentioned, as I wouldn't recommended it).

**Pull request merged**
