### PR TITLE
Bump pileup version

### PR DESCRIPTION
**Pull request by danvk**
See [pileup release notes](https://github.com/hammerlab/pileup.js/releases/tag/v0.3.0). The most notable win for Cycledash is the coverage track.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/804)

### CODE REVIEW

**Comment by ihodes** [comment]
:sparkles: :+1: :sparkles:

**Comment by danvk** [comment]
FYI I added location/scale tracks & cleared out some redundant styles (which were already coming in from `pileup.css`)

**Comment by danvk** [comment]
Still seeing odd vertical scrollbars on all tracks in Cycledash.

**Comment by danvk** [comment]
cycledash with pileup03

**Comment by ihodes** [comment]
LGTM!

**Pull request merged**
