### PR TITLE
Consolidate IGV Links

### LINKED ISSUE #618: Consolidate IGV links
The two IGV links ("load" and "jump") turn out to be unnecessary. If the tracks are already loaded in IGV, reloading them is really fast.

cc @jaclynperrone

### PR DESCRIPTION
**Pull request by danvk**
Fixes #618 

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/620)

### CODE REVIEW

**Comment by danvk** [comment]
@jaclynperrone FYI

**Comment by ihodes** [comment]
Awesome, LGTM post screenshots (we'll debug tomorrow).

**Comment by danvk** [comment]
There was a lint error that `console` wasn't defined. Since `throw`ing in the case was a problem and we _do_ want to know about missing `.bai.json` files, `console.warn` seems like a reasonable compromise.

**Comment by ihodes** [comment]
LGTM

**Comment by jaclynperrone** [comment]
Looks great here!

**Pull request merged**
