### PR TITLE
Design part two

### LINKED ISSUE #102: Tooltips should fall in the middle of the header, and should be top-oriented

### LINKED ISSUE #650: Comments redesign
Right now the comments are styled in two different ways. They are displayed as list items on the Runs page, and objects on the Examine page. The goal is to pick a direction and make them look consistent throughout the app. I'd like to play around with a timeline/activity feed approach on the Runs page, which may lend itself to how the comments are styled on the Examine page.

### LINKED ISSUE #743: Clicking a BAM file in the table causes an odd-resizing
Original table:
image

After click a single row:
image

### PR DESCRIPTION
**Pull request by jaclynperrone**
This commit touches upon a number of design things;
- Style/copy tweaks
- Closes #743
- Closes #102
- Closes #650
- VCF comparison table
- About page
- Comments page
- CQL search
- Pileup view
- Update pdiff screenshots

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/755)

### CODE REVIEW

**Comment by danvk** [comment]
Two quick comments:

1. the CQL "X" isn't centered for me:
screen shot 2015-06-23 at 11 50 25 am

2. Not sure what I think about the blue-on-blue for comments. They almost look disabled or de-emphasized to me. Also they have a gray background on the comments page but a blue background on the examine page. Do we want to be consistent about that?

screen shot 2015-06-23 at 11 55 12 am

**Comment by jaclynperrone** [comment]
I was going back and forth about the comments background! Thanks for pushing me into that direction. 

Just pushed a fix for both of those things. Thanks again for taking a look!

**Comment by danvk** [comment]
Cool! Do you need to update the screenshots again?

**Comment by jaclynperrone** [comment]
Yes! Thank you. I just pushed the updated screenshots.

**Comment by danvk** [comment]
This looks great! Thanks for the redesign :nyan:

To make the issue auto-closing work, I think you need to put `Closes #123` on its own line for each issue, e.g.

```
Closes #743
Closes #102
Closes #650
```

**Pull request merged**
