### PR TITLE
Migrate and greatly simplify Python JSON API

### PR DESCRIPTION
**Pull request by ihodes**
The goal of this PR is to simplify the JSON API, make the API more
uniform and RESTful, and provide better error messages.

Eventually the work in this PR should be used to automatically generate
documentation.

Use flask-restful
Return camel-cased JSON
Accept camel-cased JSON
Better error handling and responses
Much shorter, easier to read API code
Increase test coverage on API: comments + runs are now tested! 
Rework comments JS to use new API
Rework runs page to use new API
Rework tasks to use new API
Rework examine page to use new API
Rework tests of JS to work with new comment fields (camelcase)
Update API docs
Forms submit via AJAX, and errors show in an alert()

Later, in a different PR (https://github.com/hammerlab/cycledash/issues/621):

> Migrate to use voluptuous for `marshal_with`, and add docstring to each field in the request/response schemas. These can later be used to generate documentation.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/617)

### CODE REVIEW

**Comment by ihodes** [comment]
@danvk this is ready for you now! Let me know if you want some more orientation.

**Comment by danvk** [comment]
Thanks for cleaning this up. I left a bunch of comments scattered throughout.

So we're using Voluptuous to specify inputs and flask.restful to validate outputs? Can we have an issue to consolidate these?

I left comments in a few specific places in the tests, but we should also be using an assertions library like `nose.tools` rather than plain-old `assert`, since it will generate nicer error messages when tests fail.

---

Review status: 31 of 33 files reviewed, 23 unresolved discussions, all commit checks successful.
Reviewed files:
- API.md @ r1
- common/helpers.py @ r1
- cycledash/__init__.py @ r1
- cycledash/bams.py @ r1
- cycledash/comments.py @ r1
- cycledash/genotypes.py @ r1
- cycledash/helpers.py @ r1
- cycledash/projects.py @ r1
- cycledash/runs.py @ r1
- cycledash/static/js/comments/components/comment.js @ r1
- cycledash/static/js/examine/components/CommentBox.js @ r1
- cycledash/static/js/examine/RecordStore.js @ r1
- cycledash/static/js/runs/components/forms.js @ r1
- cycledash/static/js/runs/components/RunsPage.js @ r1
- cycledash/tasks.py @ r1
- cycledash/templates/about.html @ r1
- cycledash/templates/tasks.html @ r1
- cycledash/validations.py @ r1
- cycledash/views.py @ r1
- requirements.txt @ r1
- scripts/lint.sh @ r1
- scripts/travis-setup.sh @ r1
- tests/data/comment-db.json @ r1
- tests/js/CommentUtils.js @ r1
- tests/js/DataUtils.js @ r1
- tests/js/ExaminePage-comments-test.js @ r1
- tests/python/test.py @ r1
- tests/python/test_bams_api.py @ r1
- tests/python/test_comments_api.py @ r1
- tests/python/test_projects_api.py @ r1
- tests/python/test_runs_api.py @ r1

---

<sup>**[common/helpers.py, line 69 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmZkJq6kSUh96bChpG)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/common/helpers.py#L69)):</sup>
Shouldn't this be `to_epoch`?

---

<sup>**[cycledash/bams.py, line 28 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpm_B3v-tAYC8B-kv_E)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/bams.py#L28)):</sup>
what is `envelope='bams'`?

---

<sup>**[cycledash/comments.py, line 15 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpm_sLjPSll7gjr-qxc)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/comments.py#L15)):</sup>
Should this just be called `Comment` or `CommentType`? Or is it distinct from a type?

---

<sup>**[cycledash/comments.py, line 108 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpm_lc2HcrG64gDlbxp)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/comments.py#L108)):</sup>
mention `comment_fields` here if that's  what you mean.

---

<sup>**[cycledash/genotypes.py, line 8 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmaG-WThOxTLJszGeI)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/genotypes.py#L8)):</sup>
It looks like you're not using most of these—`pylint` should catch this.

---

<sup>**[cycledash/helpers.py, line 42 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmaSFEd_cTrqyIA_Tu)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L42)):</sup>
An example would be helpful; I don't know what "underscorize" means.

---

<sup>**[cycledash/helpers.py, line 51 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmag7qED81WJqhfZ4j)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L51)):</sup>
nit: you can put the `"""` on the previous line for one-line docstrings ([PEP 257][1])

[1]: https://www.python.org/dev/peps/pep-0257/#one-line-docstrings

---

<sup>**[cycledash/helpers.py, line 52 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmapzv3HynWDiyz9kx)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L52)):</sup>
why would you pass a list to a function called `camelcase_dict`?

---

<sup>**[cycledash/helpers.py, line 164 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmb189_IoULKN2Ppds)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L164)):</sup>
`flast`→`flask`

---

<sup>**[cycledash/helpers.py, line 193 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmbDo9sY5wWECPJQW-)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L193)):</sup>
is there a `SingleInvalid` or is this just an odd name?

---

<sup>**[cycledash/runs.py, line 33 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmbf7WdJKTSIX8AFaw)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/runs.py#L33)):</sup>
why `Raw` and not `Integer`?

---

<sup>**[cycledash/static/js/examine/RecordStore.js, line 326 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmbzrcfQIYbmP8Bsb2)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/static/js/examine/RecordStore.js#L326)):</sup>
what other fields are we setting that need to be stripped?

---

<sup>**[cycledash/static/js/runs/components/forms.js, line 19 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmc5HJ79G9ODp7PAOc)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/static/js/runs/components/forms.js#L19)):</sup>
submits

---

<sup>**[cycledash/static/js/runs/components/forms.js, line 24 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmcT-GY8fYAcRDQ3Nf)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/static/js/runs/components/forms.js#L24)):</sup>
`.find('input, textarea')`

---

<sup>**[cycledash/validations.py, line 31 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmd3SUTMiiAXUPv_EY)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/validations.py#L31)):</sup>
Add a note somewhere that these are all types for requests, not responses (whose types are scattered throughout other modules—but maybe they should all be here!).

---

<sup>**[scripts/lint.sh, line 11 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmdhhZA5tnwfdKz4Oq)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/scripts/lint.sh#L11)):</sup>
what is this disabling, exactly? I'd prefer to use `ignored-classes` if at all possible.

---

<sup>**[scripts/travis-setup.sh, line 10 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmdurVsnys581FL2AY)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/scripts/travis-setup.sh#L10)):</sup>
This is exciting!

---

<sup>**[tests/js/CommentUtils.js, line 75 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpme1lclpGGde9HJ8B4)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/js/CommentUtils.js#L75)):</sup>
do you want a delimiter?

---

<sup>**[tests/python/test.py, line 22 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmeuWMCe9m4YSUwCLB)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/python/test.py#L22)):</sup>
Write these out as:

```python
eq_('camelCase', camelcase('camel_case'))
```

Nose will generate the error messages for you.

---

<sup>**[tests/python/test_comments_api.py, line 15 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmfPPta_rTw72NBAsa)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/python/test_comments_api.py#L15)):</sup>
Does this mean the test database needs to be recreated whenever we run the tests? If so, that should be noted in `DEVELOP.md` (which currently says to run `nosetests tests/python`)

---

<sup>**[tests/python/test_comments_api.py, line 52 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmfwjdUrCsjK04KiIX)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/python/test_comments_api.py#L52)):</sup>
use `nose.tools.assert_dict_equal` or `nose.tools.assert_dict_contains_subset` here.

---

<sup>**[tests/python/test_projects_api.py, line 41 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmgVH-Lg0V6rg98qvp)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/python/test_projects_api.py#L41)):</sup>
nit: there are mixed quotes (`"` and `'`) on this line. I think we've typically tried to use just `'` in CycleDash.

---

<sup>**[tests/python/test_runs_api.py, line 51 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmgl8w4ZlPODNkb6V-)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/python/test_runs_api.py#L51)):</sup>
use `nose.tools` assertions

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/617)

**Comment by ihodes** [comment]
There is indeed already an issue for that :) https://github.com/hammerlab/cycledash/issues/621

Wrt nose.tools, sounds reasonable enough, but not devdire enough to hold up getting this PR in: I seemed to get decent error messages when an assert failed while using these tests. I've filed an issue here to track it, and we can get to it later: https://github.com/hammerlab/cycledash/issues/625

---

Review status: 19 of 36 files reviewed, 10 unresolved discussions, some commit checks pending.

---

<sup>**[common/helpers.py, line 69 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmZkJq6kSUh96bChpG)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/common/helpers.py#L69)):</sup>
Good catch!

---

<sup>**[cycledash/bams.py, line 28 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpm_B3v-tAYC8B-kv_E)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/bams.py#L28)):</sup>
It means the response is wrapped in an envelope named 'bams', e.g. `{ "bams": <resp> }`

---

<sup>**[cycledash/comments.py, line 15 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpm_sLjPSll7gjr-qxc)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/comments.py#L15)):</sup>
I think it's distinct; it specifies the fields that we allow the API to return.

---

<sup>**[cycledash/helpers.py, line 42 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmaSFEd_cTrqyIA_Tu)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L42)):</sup>
The verb comes from the function two above this one; I'll explain better in the comment since it's unclear.

---

<sup>**[cycledash/helpers.py, line 52 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpmapzv3HynWDiyz9kx)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L52)):</sup>
Because it needs to recursively apply itself to objects in lists in the dict, e.g. `{bams: [bam1, bam2, bam3]}`

---

<sup>**[cycledash/helpers.py, line 193 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmbDo9sY5wWECPJQW-)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/helpers.py#L193)):</sup>
There is a an `Invalid`, but `Schema`'s raise `MultipleInvalid`, as they raise once with all errors found in validation.

---

<sup>**[cycledash/static/js/examine/RecordStore.js, line 326 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmbzrcfQIYbmP8Bsb2)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/cycledash/static/js/examine/RecordStore.js#L326)):</sup>
`created`, for example, I believe. 

---

<sup>**[scripts/lint.sh, line 11 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmdhhZA5tnwfdKz4Oq)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/scripts/lint.sh#L11)):</sup>
This is because of `import flask.ext.restful` or `from flask.ext import restful`--it raises no-name-in-module.

---

<sup>**[tests/js/CommentUtils.js, line 75 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpme1lclpGGde9HJ8B4)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/js/CommentUtils.js#L75)):</sup>
It's been working without on—I think it's fine?

---

<sup>**[tests/python/test_comments_api.py, line 15 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-JpmfPPta_rTw72NBAsa)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/python/test_comments_api.py#L15)):</sup>
This doesn't, as comments are being deleted by the `tearDown`, but I've added a `scripts/run-python-tests.py` (and noted in DEVELOP.md) to make sure the database is in a known state before running tests, thereby preventing possible errors.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/617)

**Comment by danvk** [comment]
looks good

---

Review status: 19 of 36 files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- DEVELOP.md @ r3

---

<sup>**[tests/js/CommentUtils.js, line 75 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/617#-Jpme1lclpGGde9HJ8B4)** ([raw file](https://github.com/hammerlab/cycledash/blob/76e0136b0b22f02fecd2995c6b43dc818063e384/tests/js/CommentUtils.js#L75)):</sup>
it just feels unnecessarily risky, e.g. `chr1` position 23 would get the same key as `chr12` position 3.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/617)

**Comment by ihodes** [comment]
Makes sense—I added a colon as a delimiter.

**Pull request merged**
