### PR TITLE
Add documentation re: basic auth for API.

### LINKED ISSUE #809: Update API docs with authentication information
Using the API now requires authentication, but it's not clear how from the documentation

```
http http://cycledash.demeter.hpc.mssm.edu/api/projects --form
HTTP/1.1 401 UNAUTHORIZED
Connection: keep-alive
Content-Length: 51
Content-Type: application/json
Date: Tue, 11 Aug 2015 04:07:47 GMT
Server: nginx/1.0.15
Set-Cookie: session=eyJfaWQiOnsiIGIiOiJOR000TkdGak1UQTFabUppTldNeE1HVTBZemt3TjJWaU1EVmpNemN4WkdZPSJ9fQ.CKsGkw.iJNz-vA1qtatcPumwA7YB0yTb2A; HttpOnly; Path=/

{
    "message": "Correct username/password required."
}

```

### PR DESCRIPTION
**Pull request by ihodes**
fixes #809

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/823)

### CODE REVIEW

**Comment by armish** [comment]
only one minor suggestion towards more clarity.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[API.md, line 6 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/823#-Jy3jExO0zki6fqQwLGM)** ([raw file](https://github.com/hammerlab/cycledash/blob/726cb0ced54c5144336102a367d5943d9377dd88/API.md#L6)):</sup>
Good one :)

I know that we cannot document everything slightly related to our setup, but do you think it is worth adding a basic curl command that does a get request featuring a simple auth as an example? Not strongly opinionated on this one. Feel free to ignore this suggestion if it is pretty obvious how to do that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/823)

**Comment by ihodes** [comment]
I'm not opposed to it, though we don't show examples for the other calls, which are more annoying to make using cURL than just sending basic auth info. Is something like the below what you're looking for?

   For example, 
    ```
    curl username:password@cycledash.example.com
    ```

**Comment by armish** [comment]
if it's that easy (I didn't know that), never mind doing it :) LGTM in its current state.

**Comment by ihodes** [comment]
Basic auth is super nice; you can also add a authorization header to the request, but that's annoying; required base64 encoding nonsense. I'm all for reworking out docs + adding example for everything, a la Stripe's amazing docs; filed an issue at https://github.com/hammerlab/cycledash/issues/827

**Pull request merged**
