### PR TITLE
Fix impossible stats & regression test

### LINKED ISSUE #516: Impossible stats
The stats say "showing all 10 variants", but the numbers add up to 20:
screen shot 2015-03-05 at 12 14 06 pm

There are only ten rows in the VCF table:
screen shot 2015-03-05 at 12 15 34 pm

I assume this has something to do with the warnings React is flagging:
screen shot 2015-03-05 at 12 16 16 pm

### LINKED ISSUE #588: True Positive = 2 but only one check mark on a row
image

There are 14 rows in this set so the total count is correct, but it says 2 True and 12 False while there is only one check mark.

### PR DESCRIPTION
**Pull request by ihodes**
fixes #588 fixes #516

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/690)

### CODE REVIEW

**Comment by danvk** [comment]
Thanks for fixing this and writing the tests!

This might be a good time to put down in writing exactly how the precision/recall calculations are done, particularly in the presence of multi-sample VCFs.

---

Review status: 0 of 3 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[cycledash/genotypes.py, line 456 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4ST7mZj6zCLBPP5SL)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/cycledash/genotypes.py#L456)):</sup>
Does this mean we're requiring that the validation VCF have the same sample names as the run VCF?

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 8 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4Sj5-jx9Vi7qjkpVM)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L8)):</sup>
`get` is pretty generic to import as a top-level symbol. How about just `from cycledash import genotypes` and then use `genotypes.get` to make the context a bit clearer?

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 9 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4StNxlaiZ8OhBGGbm)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L9)):</sup>
`pick` is unused. Why isn't pylint picking this up?

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 40 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4T8Q071TCktmrf2fS)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L40)):</sup>
Are there fields in `stats` that you don't want to check? This would read more clearly if you compared `stats` with a golden dict.

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 46 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4TN-0lRhyorTt0Rjm)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L46)):</sup>
Is this really `8/12`? It feels like less of a magic number if you write it out that way.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/690)

**Comment by ihodes** [comment]
Way/a few minutes ahead of you :) https://github.com/hammerlab/cycledash/issues/691

Thanks for the review!

---

Review status: 0 of 3 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[cycledash/genotypes.py, line 456 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4ST7mZj6zCLBPP5SL)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/cycledash/genotypes.py#L456)):</sup>
No—just that we're allowing the sample_name field on the validation/comparison VCF to be filtered as well. I filed https://github.com/hammerlab/cycledash/issues/689 because this can result in confusing behavior.

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 9 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4StNxlaiZ8OhBGGbm)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L9)):</sup>
Removed & I don't know!

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 40 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4T8Q071TCktmrf2fS)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L40)):</sup>
Unfortunately there's not a great way to compare against a dict with almost_equals on float in it. Could make it, but I'm not sure it buys us much; this is very clear, and the error message is clear when it's not equal.

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 46 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4TN-0lRhyorTt0Rjm)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L46)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/690)

**Comment by danvk** [comment]
Looks good!

---

Review status: 0 of 4 files reviewed, 5 unresolved discussions, some commit checks pending.

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 40 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4T8Q071TCktmrf2fS)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L40)):</sup>
That's fine. You may not need the `_almost_equals` bit—floating points shouldn't have uncertainty for simple divisions like these.

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 41 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4iVHN1c12wTd2shVX)** ([raw file](https://github.com/hammerlab/cycledash/blob/914a79c71c94e8b54d82a10252423be834036e0e/tests/python/test_genotypes_stats_api.py#L41)):</sup>
I don't think these names really make it any more clear what's going on—feel free to take them or leave them as you like.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/690)

**Comment by ihodes** [comment]
Review status: 0 of 4 files reviewed, 5 unresolved discussions, some commit checks pending.

---

<sup>**[tests/python/test_genotypes_stats_api.py, line 40 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/690#-Jr4T8Q071TCktmrf2fS)** ([raw file](https://github.com/hammerlab/cycledash/blob/b05a55cfbd6c5b613234b5061d6c52ec2b3157a0/tests/python/test_genotypes_stats_api.py#L40)):</sup>
That's what I'd thought! It turns out they do, though.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/690)

**Pull request merged**
