### PR TITLE
Use modals

### LINKED ISSUE #600: 'New Project', 'Add BAM', and 'Add Run' buttons should trigger modals
It's helpful to keep the form separate from the files that are already submitted on the runs page. This will keep the user focused on completing the task. It will also reduce clutter and confusion.

### PR DESCRIPTION
**Pull request by jaclynperrone**
The following launches the New Project, Add BAM, and Add Run forms into modals. Would _love_ some feedback for this one. This approach features one `<Modal />` component that displays the correct form based on the state of `RunsPage`. Thoughts?
- Closes #600 

Known bug:
- The closing animation is not as smooth when you use the 'x' button. This is in comparison to using the `esc` key or clicking outside of the form to close. Any ideas for a fix? (See screenshot attached)
  bug

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/787)

### CODE REVIEW

**Comment by jaclynperrone** [comment]
Looping in @ihodes for feedback! :nyan:

**Comment by danvk** [comment]
FYI the build is failing because of a [lint check][1]:

```
Linting...
cycledash/static/js/runs/components/RunsPage.js: line 20, col 70, Missing semicolon.
cycledash/static/js/runs/components/RunsPage.js: line 122, col 79, Missing semicolon.
2 errors
```

[1]: https://travis-ci.org/hammerlab/cycledash/builds/70813869#L2055

**Comment by danvk** [comment]
Thanks for working through this, Jackie! I left a bunch of comments for you. Let me know if you need help interpreting them.

One other note about commit history in Pull Requests—I think it's good practice to squash "work in progress" commits before pushing to GitHub. In this case you could squash the first four commits (9fe2519..26f4e09) into a single commit that refactors the modal and then have a second commit that updates the screenshots.

---

Review status: 0 of 23 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/static/js/runs/components/forms.js, line 131 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC1YaylyyNpTmhuLQD)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/forms.js#L131)):</sup>
Move up to previous line

---

<sup>**[cycledash/static/js/runs/components/forms.js, line 132 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC1bPUUnZihovuXGY8)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/forms.js#L132)):</sup>
indentation is off here & below

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC2da7aMP5pk8d_JTv)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L12)):</sup>
indent two spaces inside objects

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC2pnPfMIA_iA59z-r)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L18)):</sup>
Add a comment about what this is and how to use it.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 20 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC2sD7fLwdUADyY784)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L20)):</sup>
I think this would be a better place to call `.modal('show')`, rather than in `componentDidUpdate` of its container. It will make the modal class more self-contained.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 84 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC4z4x-S-NUraT0Mio)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L84)):</sup>
So remember how I said you shouldn't call `.modal('hide')` in `closeModal()`? I think that's why you're seeing glitches in the animation. While bootstrap is animating the hide, React comes in and deletes the DOM element.

The solution is.... to call `.modal('hide')` in the `Modal` class and only call `closeModal` when the transition is complete. I can help you make that work in your skeleton code.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 109 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC4ANxFjQQw-iN2Yrj)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L109)):</sup>
indent

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 116 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC3k4Ox58pYHKHyn3u)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L116)):</sup>
indentation is odd here (and below)

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 119 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC3pB_3tktGNnwPZFw)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L119)):</sup>
If you want to pass through all the key/value pairs of an Object to a component, JSX has a shorthand:

```javascript
form = <forms.NewBAMForm {...this.state.newFormProps} />;
```

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 213 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC4NhStpDcSe_h_QBF)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L213)):</sup>
Suggest pulling these handlers out into explicit methods, e.g.

```javascript
showRunModal: function() {
  this.props.handleShowRunModal(this.props.name, this.props.project_id, this.props.bams);
}
```

and then

```javascript
<button onClick={this.showRunModal}>...</button>
```

This is clearer & it's also a performance optimization since you don't have to create a new closure on every `render` call.

---

<sup>**[cycledash/static/scss/runs.scss, line 54 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC4m-zPU3iZT8k7W69)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/scss/runs.scss#L54)):</sup>
trailing whitespace here

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by ihodes** [comment]
Review status: 0 of 23 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC758CE5sHwPglRxjP)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L18)):</sup>
(From the peanut gallery): Add `propTypes`documenting the required props for this component (`children`) and what they're expected to be.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by ihodes** [comment]
Looks great, Jacky! And a nice, clean implementation, too. :nyan: for your first (of many :) big React.js commit!

**Comment by danvk** [comment]
Review status: 0 of 23 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC758CE5sHwPglRxjP)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L18)):</sup>
Can you put `children` in `propTypes`? It's special, it's the thing that goes inside the JSX expression:

`<Modal>children go here and come out as a list of elements</Modal>`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by ihodes** [comment]
Review status: 0 of 23 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC758CE5sHwPglRxjP)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L18)):</sup>
Good point, I'm not sure if you can; regardless, it's pretty clear what it means, so @jaclynperrone ignore my comment :) 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by jaclynperrone** [comment]
@danvk I implemented all your suggestions! Would love for you to give it another look if you'd like.

Thanks!

**Comment by danvk** [comment]
Looks good — maybe @ihodes wants to take a look at the seltest changes.

---

Review status: 0 of 26 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC2da7aMP5pk8d_JTv)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L12)):</sup>
Haha, I meant "just two space", not "two more spaces". There should be a two space indentation here, not six.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 84 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC4z4x-S-NUraT0Mio)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L84)):</sup>
I think we resolved this?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by jaclynperrone** [comment]
Review status: 0 of 26 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC2da7aMP5pk8d_JTv)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L12)):</sup>
I'm still not following. Like this? http://screencast.com/t/3YcKfzye

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 75 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC4z4x-S-NUraT0Mio)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L75)):</sup>
Check out the Modal class. The updates are in there.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by ihodes** [comment]
Screenshots look good to me. The modal background being wonky is a result of how firefox does screenshots, not a big deal.

**Comment by danvk** [comment]
Review status: 0 of 26 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC2da7aMP5pk8d_JTv)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L12)):</sup>
Yep!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by jaclynperrone** [comment]
Review status: 0 of 26 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuC2da7aMP5pk8d_JTv)** ([raw file](https://github.com/hammerlab/cycledash/blob/3686be0ab52b36b69071edd25ab97e229d4f1623/cycledash/static/js/runs/components/RunsPage.js#L12)):</sup>
Interesting. My designer brain cries a little when looking at it ;)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by danvk** [comment]
Just one thing then good to go.

---

Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 24 \[r3\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuqI3GDBckpiQU3dFGt)** ([raw file](https://github.com/hammerlab/cycledash/blob/c406c52bc917600631bb326d88d679d63f305a28/cycledash/static/js/runs/components/RunsPage.js#L24)):</sup>
Can you change `() => {this.props.handleClose();}` to just `this.props.handleClose`? I think it should work.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by jaclynperrone** [comment]
Thanks for looking through it again. I think I'm going to table this branch for another time. The VCF upload issue is discouraging, and I wouldn't want to break Cycledash in that, or other ways. Thanks for all your help! I've certainly learned a lot.

---

Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by danvk** [comment]
You're positive that this change breaks VCF uploading? Let me know if you want help debugging that.

---

Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by jaclynperrone** [comment]
Not positive. It's throwing an error on my master as well. Always down for some help whenever you have the time. Would love to debug it together.

---

Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Comment by ihodes** [comment]
We figured it out! Database schema sync issues; the local DB's schema was out of sync with the schema Cycledash was expecting.

**Comment by jaclynperrone** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cycledash/static/js/runs/components/RunsPage.js, line 24 \[r3\]](https://reviewable.io:443/reviews/hammerlab/cycledash/787#-JuqI3GDBckpiQU3dFGt)** ([raw file](https://github.com/hammerlab/cycledash/blob/c406c52bc917600631bb326d88d679d63f305a28/cycledash/static/js/runs/components/RunsPage.js#L24)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/787)

**Pull request merged**
