### PR TITLE
Contig and position can be sorted by in the UI

### LINKED ISSUE #383: contig|position column sort arrows aren't in correspondance with CQL query

### PR DESCRIPTION
**Pull request by ihodes**
Fixes #383

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/426)

### CODE REVIEW

**Comment by danvk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/426)



---

Just a few comments -- it's not much more work to make the checks for contig/position sort order more robust, so we may as well. Also, we should expect several dpxdt screenshots (e.g. `examine.png`) to change as a result of this PR.

---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 81 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfnXKJqNdBZfj03yo97)** ([raw file](https://github.com/hammerlab/cycledash/blob/46847109d55e77f5961bac7021e40bf9f4b8061e/cycledash/static/js/examine/components/VCFTable.js#L81)):</sup>
Any reason to do it this way instead of just passing an array like the other methods which take `sortBys`?

---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 98 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfnYCrfzlKtUHo2xfj5)** ([raw file](https://github.com/hammerlab/cycledash/blob/46847109d55e77f5961bac7021e40bf9f4b8061e/cycledash/static/js/examine/components/VCFTable.js#L98)):</sup>
The `ORDER BY contig, position` could be at any position.

Maybe something like:

```javascript
posSorts = this.props.sortBys.filter(c => _.contains(['position', 'contig'], c.columnName)),
isSorted = posSorts.length == 2
```

---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 99 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfnY6Vjc1atqTTUvBs8)** ([raw file](https://github.com/hammerlab/cycledash/blob/46847109d55e77f5961bac7021e40bf9f4b8061e/cycledash/static/js/examine/components/VCFTable.js#L99)):</sup>
`posSorterClasses`? Took me a minute to realize that this only applied to that column.

---

**Comment by ihodes** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/426)







---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 81 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfnXKJqNdBZfj03yo97)** ([raw file](https://github.com/hammerlab/cycledash/blob/46847109d55e77f5961bac7021e40bf9f4b8061e/cycledash/static/js/examine/components/VCFTable.js#L81)):</sup>
Not particularly. Changes less code. Checking `arguments` seems pretty standard in JS.

---

**Comment by danvk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/426)



---

LGTM % 2

---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 81 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfnXKJqNdBZfj03yo97)** ([raw file](https://github.com/hammerlab/cycledash/blob/46847109d55e77f5961bac7021e40bf9f4b8061e/cycledash/static/js/examine/components/VCFTable.js#L81)):</sup>
I'm fine with using `arguments` in general, my concern is w/ the function signature here. Everywhere else we have `function(pluralNouns)` it means pass in an array, but passing in an array to this function would be a disaster.

If you want to keep this style, maybe change it to something like `function(/*columnName1, columnName2, ...*/)`?

---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 102 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfndyvLVvZeVkAFQRaz)** ([raw file](https://github.com/hammerlab/cycledash/blob/45d7d2df10abda3ab5f6a6eae43b074f878401bd/cycledash/static/js/examine/components/VCFTable.js#L102)):</sup>
`posSorts[0]` (And below)

---

**Comment by ihodes** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/426)







---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 81 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfnXKJqNdBZfj03yo97)** ([raw file](https://github.com/hammerlab/cycledash/blob/46847109d55e77f5961bac7021e40bf9f4b8061e/cycledash/static/js/examine/components/VCFTable.js#L81)):</sup>
Sounds reasonable

---

**Comment by danvk** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/426)



---

LGTM % 1

---

<sup>**[cycledash/static/js/examine/components/VCFTable.js, line 93 \[r3\]](https://reviewable.io:443/reviews/hammerlab/cycledash/426#-JfnluSuFanr4_YR9zBv)** ([raw file](https://github.com/hammerlab/cycledash/blob/2fd2bfdf02b05e1d0874c085e8b4d6f25676b803/cycledash/static/js/examine/components/VCFTable.js#L93)):</sup>
This is an unused var now -- I would've hoped `jsxhint` would complain about that.

---

**Pull request merged**
