### PR TITLE
Don't display integer array columns as sortable

### LINKED ISSUE #190: Integer array fields are typed as integers
This breaks charting

image

### PR DESCRIPTION
**Pull request by ihodes**
Also show the "num" attribute on the column tooltip

Fixes #190

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/425)

### CODE REVIEW

**Comment by danvk** [comment]
Do you need to update any of the screenshots? LGTM otherwise.

**Comment by ihodes** [comment]
I do, and on #427, but I am unable to get dpxdt running again…will give it another go tomorrow!

**Comment by danvk** [comment]
Lemme know if you want to pair on it. As usual, dpxdt has been frustratingly solid on my machine.

**Comment by ihodes** [comment]
Figured it out! Added & back to you @danvk

**Comment by danvk** [comment]
Thanks for updating the screenshot! I'm a little confused though -- I thought the point of this change was that integer list columns were previous being shown as sortable. But I don't see any sort arrows disappearing on that screenshot.

**Comment by ihodes** [comment]
None of the sort arrows were on integer lists, so we wouldn't expect any to disappear.

**Comment by danvk** [comment]
@ihodes and I discussed this on Slack:

```
[12:05 PM] dan: I guess I'm still confused what that PR is fixing
[12:05 PM] dan: if integer list columns didn't have sort arrows in the first place
[12:05 PM] isaac: they did/do
[12:06 PM] dan: what about DP4?
[12:06 PM] isaac: there were no integer lists in the set
[12:06 PM] isaac: i don't think that's an integer list
[12:06 PM] isaac: i'd imagine it's incorrectly typed
[12:07 PM] dan: could you add a test (mocha or pdiff) then?
[12:07 PM] dan: this seems like the sort of small thing that could regress
[12:07 PM] isaac: sure
```

**Comment by danvk** [comment]
Nice! Feel free to merge on Travis green.

**Pull request merged**
