### PR TITLE
Login & authentication

### LINKED ISSUE #709: User accounts and basic ACL
This is necessary for supporting external users.

Lots of options with Flask, this shouldn't be much more than some decorators on routes + some migrations.

### PR DESCRIPTION
**Pull request by ihodes**
Resolves #709 

This PR adds basic authentication to Cycledash, both to the API code + to the frontend views. It also includes a simple registration system (anyone can register at this point; there is no account activation). All objects are available to any logged in user (there is no ACL of any kind).

The system brcrypts the password and stores it in the user table (migration code below) along with a username and email address. 

Future plans include:
- LDAP auth https://github.com/hammerlab/cycledash/issues/772
- ACL + groups for object access https://github.com/hammerlab/cycledash/issues/770
- Email verification + user auth/activation (admins, basically) https://github.com/hammerlab/cycledash/issues/771

Highlights:
- Add user object + validations
- Add login/registration/logout code
- Add authentication code
- Modify tests to automatically handle basic auth (+ other repetitive code)
- Add tests for authentication

Migration code:

``` sql
CREATE TABLE users (
       id BIGSERIAL PRIMARY KEY,
       username TEXT UNIQUE NOT NULL,
       password TEXT NOT NULL,
       email TEXT UNIQUE NOT NULL
);
```

**TODO**
- [x] Finish login/logout/registration 
- [x] Add authentication to API
- [x] Tests
- [x] pdiff tests (need to be logged in for tests now!)
- [x] Test updates for existing tests
- [x] Notion of user groups/ACL (probably push & file)

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/769)

### CODE REVIEW

**Comment by hammer** [comment]
Have you filed an issue for integration with LDAP?

**Comment by ihodes** [comment]
Filed https://github.com/hammerlab/cycledash/issues/772

**Comment by danvk** [comment]
Thanks for doing this! Most of my comments are small.

Now that we have accounts, we don't need the "username" field when you're filling out comments. Can you drop that, or file an issue to do so in a follow-up?

---

Reviewed 39 of 65 files at r1.
Review status: 39 of 65 files reviewed at latest revision, 23 unresolved discussions, all commit checks successful.

---

<sup>**[config.py, line 7 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ4qbBTvjypVbJXUcZ)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/config.py#L7)):</sup>
This is kinda hard to grok. Is it the same as

```python
if not value or value.lower() == 'false':
```

---

<sup>**[config.py, line 34 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ56WUdze5L2kShOIH)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/config.py#L34)):</sup>
I like that this is required to be set!

---

<sup>**[cycledash/api/__init__.py, line 10 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ5guzuyl3N1dyXze3)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/api/__init__.py#L10)):</sup>
Does `flask.ext.restful` not have built-in support for authentication?

---

<sup>**[cycledash/api/__init__.py, line 14 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ5wJ_CTwh2w7aNWxW)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/api/__init__.py#L14)):</sup>
`self.require_auth`

(It's more descriptive and avoids having two names for the same thing.)

---

<sup>**[cycledash/api/__init__.py, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ6uA4hD7lLev7pXhg)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/api/__init__.py#L18)):</sup>
It might be cleaner to make this class `AuthenticatedResource`, ditch the `require_auth` property and use `flask.ext.Resource` when you don't care about authorization. This class is a no-op is `require_auth=False`.

---

<sup>**[cycledash/api/projects.py, line 13 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ7b4sTMebmd5sWUkB)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/api/projects.py#L13)):</sup>
why the rename? (In general, if we want to call this `tasksapi`, I think we should name the file `tasksapi.py`.)

---

<sup>**[cycledash/auth.py, line 1 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ8NQrLKMD5ixI92fl)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/auth.py#L1)):</sup>
docstring

---

<sup>**[cycledash/auth.py, line 40 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ8WRZi2n9_8Zrrjt7)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/auth.py#L40)):</sup>
"it exists", "the password"

---

<sup>**[cycledash/auth.py, line 55 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ8p_1NMJ9uAEt1ckU)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/auth.py#L55)):</sup>
Does flask-login force these to be methods? (I'd expect them to be `@property`)

---

<sup>**[cycledash/auth.py, line 106 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ9_3YsdDd4sS5A9ia)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/auth.py#L106)):</sup>
Why not use `wrap_user` or `class User` here?

---

<sup>**[cycledash/auth.py, line 108 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ9Pcrjlsssf_MDk3y)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/auth.py#L108)):</sup>
Here `is_authenticated` is `True` whereas in the `User` class `is_authenticated` is a method which returns `True`. Is the distinction intentional?

---

<sup>**[cycledash/templates/layouts/layout.html, line 5 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZA7met2zdR5eiYjCm)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/templates/layouts/layout.html#L5)):</sup>
A momentous change!

---

<sup>**[cycledash/templates/login.html, line 9 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZG9LhPoz-QWV_2QSH)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/templates/login.html#L9)):</sup>
In the screenshot tests, the "Login" text is wrapped to the next line (`website_login.png`).

---

<sup>**[cycledash/templates/login.html, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZAqRknyMywT9GA4ym)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/templates/login.html#L12)):</sup>
I think "Login" = noun, "Log in" = verb. When I visit facebook.com, for example, the button to sign in is "Log In", two words.

---

<sup>**[cycledash/templates/macros/nav.html, line 22 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZBWKnXYf3Gj_7G1gH)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/templates/macros/nav.html#L22)):</sup>
"Log Out" (c.f. Facebook)

---

<sup>**[cycledash/templates/register.html, line 27 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZCK4WhNPjAikVxXvy)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/templates/register.html#L27)):</sup>
It would be helpful to indicate the password requirements somewhere on the form, e.g. "your password must be eight or more characters"

---

<sup>**[cycledash/views.py, line 16 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZCWUuBZSShHTOT2VB)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/views.py#L16)):</sup>
I'm not comfortable with having two variables that differ only in capitalization. Using `api.api` wouldn't bother me.

---

<sup>**[cycledash/views.py, line 90 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZD9qmryeqNTsfhWWl)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/views.py#L90)):</sup>
Can we use `@login_required` for `Resource`s as well?

---

<sup>**[scripts/travis-run-pdiff-tests.sh, line 11 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZDO_4FIFU2x9vkqQY)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/scripts/travis-run-pdiff-tests.sh#L11)):</sup>
Any reason this needs to be on the same line as `python run.py`?

---

<sup>**[tests/python/helpers.py, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZE8kKOjKy-qcAeuNU)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/tests/python/helpers.py#L12)):</sup>
This seems really similar to `auth.register`. Can you just use that?

---

<sup>**[tests/python/test_authentication.py, line 26 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZEYyP3OsOyiOUn13r)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/tests/python/test_authentication.py#L26)):</sup>
rm debug code.

---

<sup>**[tests/python/test_authentication.py, line 65 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZElJ9hkW4H3SToCEh)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/tests/python/test_authentication.py#L65)):</sup>
One downside of doing it this way (instead of `eq_(401, ...)` on every line) is that, if any of these return a different code, you'll have a harder time figuring out which one it was.

---

<sup>**[tests/python/test_comments_api.py, line 36 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZFBPzHztc5z6Lxt-m)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/tests/python/test_comments_api.py#L36)):</sup>
Won't `ResourceTest` do this anyway? (Same comment on the other resource test modules.)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/769)

**Comment by ihodes** [comment]
filed https://github.com/hammerlab/cycledash/issues/779

---

Review status: 29 of 65 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/api/__init__.py, line 10 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ5guzuyl3N1dyXze3)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/api/__init__.py#L10)):</sup>
It does not.

---

<sup>**[cycledash/api/__init__.py, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ6uA4hD7lLev7pXhg)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/api/__init__.py#L18)):</sup>
I'd rather use the same class for all API resources. This class'll be extended to handle generating docs etc. 

---

<sup>**[cycledash/auth.py, line 55 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZ8p_1NMJ9uAEt1ckU)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/auth.py#L55)):</sup>
Yes, the current release forces these to be methods. The upcoming release changes this to properties.

---

<sup>**[cycledash/views.py, line 90 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZD9qmryeqNTsfhWWl)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/cycledash/views.py#L90)):</sup>
We could rewrite @login_required and use it for it, but they're doing different things right now.

---

<sup>**[scripts/travis-run-pdiff-tests.sh, line 11 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZDO_4FIFU2x9vkqQY)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/scripts/travis-run-pdiff-tests.sh#L11)):</sup>
Nope, I'll move it out of line.

---

<sup>**[tests/python/helpers.py, line 12 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZE8kKOjKy-qcAeuNU)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/tests/python/helpers.py#L12)):</sup>
`auth.register` is specific to the flask request context, so wouldn't work here.

---

<sup>**[tests/python/test_authentication.py, line 65 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZElJ9hkW4H3SToCEh)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/tests/python/test_authentication.py#L65)):</sup>
The debug print statement above (now removed) makes it quite easy to debug in practice (I had to use it to debug in fact).

---

<sup>**[tests/python/test_comments_api.py, line 36 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/769#-JtZFBPzHztc5z6Lxt-m)** ([raw file](https://github.com/hammerlab/cycledash/blob/4b831f14a834bcfaf880854370dcfab77051c513/tests/python/test_comments_api.py#L36)):</sup>
It would do this at the end of the quite, but not at the end of each test case (as this does)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/769)

**Comment by danvk** [comment]
LGTM

---

Review status: 29 of 65 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/769)

**Comment by ihodes** [comment]
Thanks for the review!

**Pull request merged**
