### PR TITLE
Examine page: remove mysterious vertical space within pileup track elements

### PR DESCRIPTION
**Pull request by armish**
See #805 for more context.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/811)

### CODE REVIEW

**Comment by danvk** [comment]
Can you make this change in pileup, rather than cycledash?

**Comment by armish** [comment]
Sure @danvk, I can do that; but I thought we were having this problem because of the custom CSS used in Cycledash. We don't see this behavior in pileup.js demo page, right? Or do you want to just make sure that this never happens when using pileup.js? If so, I will do the changes in pileup.

**Comment by danvk** [comment]
This is the vertical scrolling issue, right? I'm pretty sure that does
happen in the pileup demo, too, but please double check!

**Comment by armish** [comment]
yeah, this addresses the vertical scrolling issue. I wasn't able to replicate this using the latest pileup.js code and the playground example we have there:

screen shot 2015-08-20 at 4 18 30 pm

Having said this, I also don't know and wasn't able to find which CSS property triggers this behavior in Cycledash :\ I will take another look and update/move the PR if I can nail it down.

**Comment by danvk** [comment]
Cool. You may be able to scroll tracks in the demo even if you can't see a
scroll bar (using the mouse wheel)

**Comment by armish** [comment]
@danvk: cannot replicate these mysterious space problem within pileup.js. I am assining this PR to you so that when you are back, we can take a look at it together and decide where to make these changes.

**Pull request merged**
