### PR TITLE
Fix project notes

### LINKED ISSUE #728: The project notes paragraph should not appear if there are no notes
Right now, the `p.notes` block appears in the Project card even if it is empty. Let's just not have it show up at all if there are no notes. This will allow me to add a `margin-top` to it, which I can't do now without it throwing the layout off.
p notes

### PR DESCRIPTION
**Pull request by jaclynperrone**
Resolves #728

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/834)

### CODE REVIEW

**Comment by ihodes** [comment]
LGTM pending green!

Do you know why the non-examine page screenshots changed?

**Comment by jaclynperrone** [comment]
@ihodes thanks!

Unfortunately, I have no idea :( They looked the same to me. The only difference I saw in webdiff was the file size.

**Comment by ihodes** [comment]
:cry: No pixel difference at all (hit "p" in webdiff)?

**Comment by jaclynperrone** [comment]
@ihodes: the pixel difference is pretty vague: http://screencast.com/t/dcheUz3Fx

**Pull request merged**
