### PR TITLE
numpy is now a requirement for convenience

### PR DESCRIPTION
**Pull request by armish**
A vanilla Mac OS fails to install these requirements if numpy is not installed before doing `pip install -r requirements.txt`. Specifically, `bdist_wheel` cannot be installed for `biopython` without `numpy`.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/656)

### CODE REVIEW

**Comment by ihodes** [comment]
Did you spot what what requiring Biopython? AFAIK we don't use it or numpy anywhere.

**Comment by armish** [comment]
Sorry for not including the log earlier. Here it is:

```text
$ pip install -r requirements.txt    # Install python requirements into virtualenv
Collecting beautifulsoup4 (from -r requirements.txt (line 1))
  Downloading beautifulsoup4-4.3.2.tar.gz (143kB)
    100% |████████████████████████████████| 143kB 1.3MB/s 
Collecting coverage (from -r requirements.txt (line 2))
  Downloading coverage-3.7.1.tar.gz (284kB)
    100% |████████████████████████████████| 286kB 889kB/s 
Collecting Flask-SQLAlchemy==1.0 (from -r requirements.txt (line 3))
  Downloading Flask-SQLAlchemy-1.0.tar.gz (92kB)
    100% |████████████████████████████████| 94kB 2.5MB/s 
Collecting Flask==0.10.1 (from -r requirements.txt (line 4))
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 544kB 455kB/s 
Collecting Jinja2==2.7.2 (from -r requirements.txt (line 5))
  Downloading Jinja2-2.7.2.tar.gz (378kB)
    100% |████████████████████████████████| 380kB 826kB/s 
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 6))
  Downloading MarkupSafe-0.23.tar.gz
Collecting PyVCF==0.6.7 (from -r requirements.txt (line 7))
  Downloading PyVCF-0.6.7.tar.gz
Collecting SQLAlchemy==1.0.4 (from -r requirements.txt (line 8))
  Downloading SQLAlchemy-1.0.4.tar.gz (4.6MB)
    100% |████████████████████████████████| 4.6MB 60kB/s 
Collecting Werkzeug==0.9.4 (from -r requirements.txt (line 9))
  Downloading Werkzeug-0.9.4.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 241kB/s 
Collecting amqp==1.4.5 (from -r requirements.txt (line 10))
  Downloading amqp-1.4.5-py27-none-any.whl (49kB)
    100% |████████████████████████████████| 53kB 3.4MB/s 
Collecting anyjson==0.3.3 (from -r requirements.txt (line 11))
  Downloading anyjson-0.3.3.tar.gz
Collecting bai-indexer==0.1.1 (from -r requirements.txt (line 12))
  Downloading bai-indexer-0.1.1.tar.gz
Collecting billiard==3.3.0.18 (from -r requirements.txt (line 13))
  Downloading billiard-3.3.0.18.tar.gz (150kB)
    100% |████████████████████████████████| 151kB 1.3MB/s 
Collecting celery==3.1.12 (from -r requirements.txt (line 14))
  Downloading celery-3.1.12-py2.py3-none-any.whl (513kB)
    100% |████████████████████████████████| 516kB 352kB/s 
Collecting itsdangerous==0.24 (from -r requirements.txt (line 15))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 49kB 3.9MB/s 
Collecting kombu==3.0.20 (from -r requirements.txt (line 16))
  Downloading kombu-3.0.20-py2.py3-none-any.whl (207kB)
    100% |████████████████████████████████| 208kB 1.3MB/s 
Collecting nose==1.3.3 (from -r requirements.txt (line 17))
  Downloading nose-1.3.3.tar.gz (274kB)
    100% |████████████████████████████████| 278kB 970kB/s 
Collecting plone.memoize==1.1.1 (from -r requirements.txt (line 18))
  Downloading plone.memoize-1.1.1.zip (52kB)
    100% |████████████████████████████████| 53kB 2.7MB/s 
Collecting pysam==0.7.8 (from -r requirements.txt (line 19))
  Downloading pysam-0.7.8.tar.gz (904kB)
    100% |████████████████████████████████| 905kB 320kB/s 
Collecting pytz==2014.4 (from -r requirements.txt (line 20))
  Downloading pytz-2014.4.tar.bz2 (159kB)
    100% |████████████████████████████████| 159kB 1.6MB/s 
Collecting pywebhdfs==0.2.3 (from -r requirements.txt (line 21))
  Downloading pywebhdfs-0.2.3.tar.gz
Collecting requests==2.3.0 (from -r requirements.txt (line 22))
  Downloading requests-2.3.0-py2.py3-none-any.whl (452kB)
    100% |████████████████████████████████| 454kB 611kB/s 
Collecting voluptuous==0.8.7 (from -r requirements.txt (line 23))
  Downloading voluptuous-0.8.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7 (from -r requirements.txt (line 24))
Collecting dpxdt==0.1.5 (from -r requirements.txt (line 25))
  Downloading dpxdt-0.1.5.tar.gz (71kB)
    100% |████████████████████████████████| 73kB 1.8MB/s 
Collecting psycopg2==2.5.4 (from -r requirements.txt (line 26))
  Downloading psycopg2-2.5.4.tar.gz (682kB)
    100% |████████████████████████████████| 684kB 403kB/s 
Collecting pylint==1.4.1 (from -r requirements.txt (line 27))
  Downloading pylint-1.4.1-py2.py3-none-any.whl (425kB)
    100% |████████████████████████████████| 425kB 706kB/s 
Collecting humanize==0.5.1 (from -r requirements.txt (line 28))
  Downloading humanize-0.5.1.tar.gz
Collecting pyensembl==0.5.13 (from -r requirements.txt (line 29))
  Downloading pyensembl-0.5.13.tar.gz (51kB)
    100% |████████████████████████████████| 53kB 4.0MB/s 
Collecting mock==1.0.1 (from -r requirements.txt (line 30))
  Downloading mock-1.0.1.tar.gz (818kB)
    100% |████████████████████████████████| 819kB 327kB/s 
Collecting flask-restful==0.3.2 (from -r requirements.txt (line 31))
  Downloading Flask_RESTful-0.3.2-py2.py3-none-any.whl
Collecting seltest==0.2.2 (from -r requirements.txt (line 32))
  Downloading seltest-0.2.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python2.7/site-packages (from Flask-SQLAlchemy==1.0->-r requirements.txt (line 3))
Collecting distribute (from PyVCF==0.6.7->-r requirements.txt (line 7))
  Downloading distribute-0.7.3.zip (145kB)
    100% |████████████████████████████████| 147kB 1.6MB/s 
Collecting zope.annotation (from plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.annotation-4.4.1.tar.gz
Collecting zope.component (from plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.component-4.2.1.tar.gz (462kB)
    100% |████████████████████████████████| 462kB 642kB/s 
Collecting zope.interface (from plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.interface-4.1.2.tar.gz (919kB)
    100% |████████████████████████████████| 921kB 322kB/s 
Collecting zope.ramcache (from plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.ramcache-2.1.0.tar.gz
Collecting cython>=0.17 (from pysam==0.7.8->-r requirements.txt (line 19))
  Downloading Cython-0.22-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 77kB/s 
Collecting PyYAML (from dpxdt==0.1.5->-r requirements.txt (line 25))
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 249kB 1.1MB/s 
Collecting python-gflags (from dpxdt==0.1.5->-r requirements.txt (line 25))
  Downloading python-gflags-2.0.tar.gz (65kB)
    100% |████████████████████████████████| 65kB 3.3MB/s 
Collecting poster (from dpxdt==0.1.5->-r requirements.txt (line 25))
  Downloading poster-0.8.1.tar.gz
Collecting pyimgur (from dpxdt==0.1.5->-r requirements.txt (line 25))
  Downloading pyimgur-0.5.2.tar.gz
Collecting logilab-common>=0.53.0 (from pylint==1.4.1->-r requirements.txt (line 27))
  Downloading logilab-common-0.63.2.tar.gz (196kB)
    100% |████████████████████████████████| 200kB 1.2MB/s 
Collecting six (from pylint==1.4.1->-r requirements.txt (line 27))
  Downloading six-1.9.0-py2.py3-none-any.whl
Collecting astroid>=1.3.3 (from pylint==1.4.1->-r requirements.txt (line 27))
  Downloading astroid-1.3.6-py2.py3-none-any.whl (182kB)
    100% |████████████████████████████████| 184kB 1.5MB/s 
Collecting typechecks>=0.0.2 (from pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading typechecks-0.0.2.tar.gz
Collecting numpy>=1.7 (from pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading numpy-1.9.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 74kB/s 
Collecting pandas>=0.13.1 (from pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading pandas-0.16.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (7.3MB)
    100% |████████████████████████████████| 7.3MB 42kB/s 
Collecting datacache>=0.4.11 (from pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading datacache-0.4.14.tar.gz
Collecting pyfaidx>=0.3.4 (from pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading pyfaidx-0.4.1.tar.gz
Collecting memoized-property>=1.0.2 (from pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading memoized-property-1.0.2.tar.gz
Collecting aniso8601>=0.82 (from flask-restful==0.3.2->-r requirements.txt (line 31))
  Downloading aniso8601-1.0.0.tar.gz (44kB)
    100% |████████████████████████████████| 45kB 4.4MB/s 
Collecting selenium (from seltest==0.2.2->-r requirements.txt (line 32))
  Downloading selenium-2.45.0.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB 111kB/s 
Collecting docopt (from seltest==0.2.2->-r requirements.txt (line 32))
  Downloading docopt-0.6.2.tar.gz
Collecting Pillow (from seltest==0.2.2->-r requirements.txt (line 32))
  Downloading Pillow-2.8.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.8MB)
    100% |████████████████████████████████| 2.8MB 96kB/s 
Collecting zope.location (from zope.annotation->plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.location-4.0.3.tar.gz (154kB)
    100% |████████████████████████████████| 155kB 806kB/s 
Collecting zope.proxy (from zope.annotation->plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.proxy-4.1.5.tar.gz (272kB)
    100% |████████████████████████████████| 274kB 1.0MB/s 
Collecting zope.event (from zope.component->plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.event-4.0.3.tar.gz (390kB)
    100% |████████████████████████████████| 393kB 674kB/s 
Collecting persistent (from zope.ramcache->plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading persistent-4.1.0.tar.gz (712kB)
    100% |████████████████████████████████| 716kB 417kB/s 
Collecting zope.testing (from zope.ramcache->plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.testing-4.1.3.tar.gz (50kB)
    100% |████████████████████████████████| 53kB 3.6MB/s 
Collecting python-dateutil (from pandas>=0.13.1->pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB)
    100% |████████████████████████████████| 192kB 372kB/s 
Collecting appdirs>=1.4.0 (from datacache>=0.4.11->pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Collecting progressbar33>=2.4 (from datacache>=0.4.11->pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading progressbar33-2.4.tar.gz
Collecting biopython>=1.65 (from datacache>=0.4.11->pyensembl==0.5.13->-r requirements.txt (line 29))
  Downloading biopython-1.65.tar.gz (12.6MB)
    100% |████████████████████████████████| 12.6MB 15kB/s 
Collecting zope.schema>=4.2.2 (from zope.location->zope.annotation->plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.schema-4.4.2.tar.gz (252kB)
    100% |████████████████████████████████| 253kB 1.1MB/s 
Collecting zope.exceptions (from zope.testing->zope.ramcache->plone.memoize==1.1.1->-r requirements.txt (line 18))
  Downloading zope.exceptions-4.0.7.tar.gz (413kB)
    100% |████████████████████████████████| 413kB 281kB/s 
Building wheels for collected packages: beautifulsoup4, coverage, Flask-SQLAlchemy, Flask, Jinja2, MarkupSafe, PyVCF, SQLAlchemy, Werkzeug, anyjson, bai-indexer, billiard, itsdangerous, nose, plone.memoize, pysam, pytz, pywebhdfs, voluptuous, dpxdt, psycopg2, humanize, pyensembl, mock, seltest, distribute, zope.annotation, zope.component, zope.interface, zope.ramcache, PyYAML, python-gflags, poster, pyimgur, logilab-common, typechecks, datacache, pyfaidx, memoized-property, aniso8601, selenium, docopt, zope.location, zope.proxy, zope.event, persistent, zope.testing, progressbar33, biopython, zope.schema, zope.exceptions
  Running setup.py bdist_wheel for beautifulsoup4
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/1e/cb/98/51c990f41ef2e80e3b72e8fe0ffc2c6e0bd8a7bd2dabbb9938
  Running setup.py bdist_wheel for coverage
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/1c/2d/55/470890618558cacad65599407445c2a1636222bd896c9023f3
  Running setup.py bdist_wheel for Flask-SQLAlchemy
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/37/d1/ad/65f6e311faab0acc4434e5d13a98433e8895c1c00109651b6c
  Running setup.py bdist_wheel for Flask
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/d2/db/61/cb9b80526b8f3ba89248ec0a29d6da1bb6013681c930fca987
  Running setup.py bdist_wheel for Jinja2
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/a2/02/21/3b4c384abea556da5c249731645581e9befc74d9d2fc9c20b5
  Running setup.py bdist_wheel for MarkupSafe
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
  Running setup.py bdist_wheel for PyVCF
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/68/93/6c/fb55ca4381dbf51fb37553cee72c62703fd9b856eee8e7febf
  Running setup.py bdist_wheel for SQLAlchemy
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/67/64/69/cf874e9414940b6260cb064394f4e072dae7da03d4a937d05a
  Running setup.py bdist_wheel for Werkzeug
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/fd/08/14/ae02a3d900a3c77ac22f05f022a65fc3c0c1c640d1bc8ddb06
  Running setup.py bdist_wheel for anyjson
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/3d/9e/de/9bd4afad0b092b039d7b6414f34a1350c53f0bc15fa6bf0647
  Running setup.py bdist_wheel for bai-indexer
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/04/52/88/8c62b9753120c3d4a03174f43c1b6b9b95f5a9e367beaff8d2
  Running setup.py bdist_wheel for billiard
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/df/a1/15/9386347503f8f37ef95a71c166acd438253c38ab9ce084357c
  Running setup.py bdist_wheel for itsdangerous
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/97/c0/b8/b37c320ff57e15f993ba0ac98013eee778920b4a7b3ebae3cf
  Running setup.py bdist_wheel for nose
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/cd/20/a0/0d909cdb2cb8dd65e4b90483808cd1ca3bcc676550c3eb610f
  Running setup.py bdist_wheel for plone.memoize
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/ee/f0/de/2dcf3b0dafae4695440313cc51b6e69ed96b79525945535c3d
  Running setup.py bdist_wheel for pysam
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/54/a0/cd/d90157074e9a9e079ce6e82a3467a38f9a2d7272db951c6dd6
  Running setup.py bdist_wheel for pytz
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/19/72/88/5910e4cbb8e13862e254680a852e18ca37ac8973649b78b3cd
  Running setup.py bdist_wheel for pywebhdfs
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/7c/14/04/925d7fbd9ff2d4f4ea7dbcef3a7a37d30eadeeba6d39649d04
  Running setup.py bdist_wheel for voluptuous
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/41/76/19/7f0417f90f2a4d7d52659ff954efa9ca2a19768e7444ac42a4
  Running setup.py bdist_wheel for dpxdt
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/46/73/bb/eedde02d10859237a427a66ed8a00d5995b4dc43996f38ff8d
  Running setup.py bdist_wheel for psycopg2
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/69/af/49/940fa4ad822f0c61b27d6ab73f064c2c6eebbb81d014fedf7d
  Running setup.py bdist_wheel for humanize
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/32/72/c9/99d4694cfbcba95ea57bc0665876f84bcff33fd214fd727bda
  Running setup.py bdist_wheel for pyensembl
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/68/50/90/82fae59792f08aa2aeaef6d0a9a0df1846a55ffcfd743c1019
  Running setup.py bdist_wheel for mock
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/c9/b4/72/4de2802cbc4bfd82f938ff92015e1b42f01131583675ab4d00
  Running setup.py bdist_wheel for seltest
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/37/65/a7/bf6772d9164ae0604c5b53ecd57f75c9fc9b197f1b42dcdbd4
  Running setup.py bdist_wheel for distribute
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/b2/3c/64/772be880a32a0c41e64b56b13c25450ff31cf363670d3bc576
  Running setup.py bdist_wheel for zope.annotation
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/0f/05/10/843026abfb085556285855ddbb051a659300c22b5a16451d7e
  Running setup.py bdist_wheel for zope.component
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/4c/0a/3b/43786086acd6277c01c7e8b4d556efbef4ba54204ca7c22b79
  Running setup.py bdist_wheel for zope.interface
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/a0/10/c4/3b2e14dad063e87d188eb2503861413db1fea43ded77834299
  Running setup.py bdist_wheel for zope.ramcache
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/36/9d/fa/dd79c8c8977b5e3bd168f68f67aff33802c2bb0436fe06d022
  Running setup.py bdist_wheel for PyYAML
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/fa/db/f6/dee55793d344f1706dc4a5a693298f0115241d1085cc212364
  Running setup.py bdist_wheel for python-gflags
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/43/11/5c/e523e162bd71f1626195d1531001f6ab88570c794a90d958f2
  Running setup.py bdist_wheel for poster
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/db/dd/c7/5697e2e095b0d6a78c9f8d4899b15c9cd5513bf524e7f438a2
  Running setup.py bdist_wheel for pyimgur
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/c2/4b/27/0c6046112d0898bd92212db79770bd7d0ba144bfa6746d41df
  Running setup.py bdist_wheel for logilab-common
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/84/d1/f0/ae52baf7327ac17350c581377536ba60336bbebe1ee729cf01
  Running setup.py bdist_wheel for typechecks
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/db/31/15/e35765125e60611a76f112e8af4f3f3f55f9e81c102f0e92ee
  Running setup.py bdist_wheel for datacache
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/b0/3c/d1/8bc07aafb06749b8ac31c13ef76884bebdc28d72c76c8ab47a
  Running setup.py bdist_wheel for pyfaidx
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/d4/07/e0/714cdc8cc11089184c73aaf03be32fc1292dd89a31fe69f73a
  Running setup.py bdist_wheel for memoized-property
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/2e/11/80/98a3f16f456560fc23be09a9786dea8ad8edfde68abee4ad2f
  Running setup.py bdist_wheel for aniso8601
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/01/2b/7d/58112b3a51bd81e9b1d945adc1a2aa26f5582f56a98967ab9e
  Running setup.py bdist_wheel for selenium
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/d5/2c/b9/f4ed689777dbac1711382642d95ce69b26c8ec74bf0152ef84
  Running setup.py bdist_wheel for docopt
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/0d/5c/a7/cb986749520c1950217b5d8405def5c18541322dbc411a80d1
  Running setup.py bdist_wheel for zope.location
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/9a/06/66/e60c6ce06f47ae4d06de8fc59b1f721768e26a1f5b4b893406
  Running setup.py bdist_wheel for zope.proxy
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/e7/b9/41/15b8c39e53b2513dd70e834e48ba93c94007f65972e9335de1
  Running setup.py bdist_wheel for zope.event
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/0d/12/49/e4a7046f78a989952bb6981e8c15a9a05a636f666fa0d73816
  Running setup.py bdist_wheel for persistent
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/ac/9f/0b/0beed0aca0106e9b073803dc4b06a6ca826d13ddc9c00897a0
  Running setup.py bdist_wheel for zope.testing
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/8b/a9/99/86ad2de19c8c10391449896e5d4d74b1098cb0970c48332ff2
  Running setup.py bdist_wheel for progressbar33
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/45/28/b7/7c16daba906507ff2b193b3038b631dd905072a764ad747fbb
  Running setup.py bdist_wheel for biopython
  Complete output from command /Users/aksoyb/Projects/cycledash/venv/bin/python2.7 -c "import setuptools;__file__='/private/var/folders/pj/_cjj7cm12zv06bsr1l7jd84mt59k64/T/pip-build-5YNC9o/biopython/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/pj/_cjj7cm12zv06bsr1l7jd84mt59k64/T/tmpAk0sHzpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  
  Numerical Python (NumPy) is not installed.
  
  This package is required for many Biopython features.  Please install
  it before you install Biopython. You can install Biopython anyway, but
  anything dependent on NumPy will not work. If you do this, and later
  install NumPy, you should then re-install Biopython.
  
  You can find NumPy at http://www.numpy.org
  
  
  ----------------------------------------
  Failed building wheel for biopython
  Running setup.py bdist_wheel for zope.schema
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/a6/7e/77/bf22dc1f327a02748a05a82889f4f6d5e19c138cbfbeac392b
  Running setup.py bdist_wheel for zope.exceptions
  Stored in directory: /Users/aksoyb/Library/Caches/pip/wheels/67/20/e7/1c19c7ba0ed1afe2d1f1715da38254736523bdbbf3d76652bc
Successfully built beautifulsoup4 coverage Flask-SQLAlchemy Flask Jinja2 MarkupSafe PyVCF SQLAlchemy Werkzeug anyjson bai-indexer billiard itsdangerous nose plone.memoize pysam pytz pywebhdfs voluptuous dpxdt psycopg2 humanize pyensembl mock seltest distribute zope.annotation zope.component zope.interface zope.ramcache PyYAML python-gflags poster pyimgur logilab-common typechecks datacache pyfaidx memoized-property aniso8601 selenium docopt zope.location zope.proxy zope.event persistent zope.testing progressbar33 zope.schema zope.exceptions
Failed to build biopython
Installing collected packages: beautifulsoup4, coverage, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, SQLAlchemy, Flask-SQLAlchemy, distribute, PyVCF, amqp, anyjson, bai-indexer, billiard, kombu, pytz, celery, nose, zope.interface, zope.event, zope.component, zope.schema, zope.proxy, zope.location, zope.annotation, persistent, zope.exceptions, zope.testing, zope.ramcache, plone.memoize, cython, pysam, requests, pywebhdfs, voluptuous, PyYAML, python-gflags, poster, pyimgur, dpxdt, psycopg2, six, logilab-common, astroid, pylint, humanize, typechecks, numpy, python-dateutil, pandas, appdirs, progressbar33, biopython, datacache, pyfaidx, memoized-property, pyensembl, mock, aniso8601, flask-restful, selenium, docopt, Pillow, seltest
  Running setup.py install for biopython
Successfully installed Flask-0.10.1 Flask-SQLAlchemy-1.0 Jinja2-2.7.2 MarkupSafe-0.23 Pillow-2.8.1 PyVCF-0.6.7 PyYAML-3.11 SQLAlchemy-1.0.4 Werkzeug-0.9.4 amqp-1.4.5 aniso8601-1.0.0 anyjson-0.3.3 appdirs-1.4.0 astroid-1.3.6 bai-indexer-0.1.1 beautifulsoup4-4.3.2 billiard-3.3.0.18 biopython-1.65 celery-3.1.12 coverage-3.7.1 cython-0.22 datacache-0.4.14 distribute-0.7.3 docopt-0.6.2 dpxdt-0.1.5 flask-restful-0.3.2 humanize-0.5.1 itsdangerous-0.24 kombu-3.0.20 logilab-common-0.63.2 memoized-property-1.0.2 mock-1.0.1 nose-1.3.3 numpy-1.9.2 pandas-0.16.1 persistent-4.1.0 plone.memoize-1.1.1 poster-0.8.1 progressbar33-2.4 psycopg2-2.5.4 pyensembl-0.5.13 pyfaidx-0.4.1 pyimgur-0.5.2 pylint-1.4.1 pysam-0.7.8 python-dateutil-2.4.2 python-gflags-2.0 pytz-2014.4 pywebhdfs-0.2.3 requests-2.3.0 selenium-2.45.0 seltest-0.2.2 six-1.9.0 typechecks-0.0.2 voluptuous-0.8.7 zope.annotation-4.4.1 zope.component-4.2.1 zope.event-4.0.3 zope.exceptions-4.0.7 zope.interface-4.1.2 zope.location-4.0.3 zope.proxy-4.1.5 zope.ramcache-2.1.0 zope.schema-4.4.2 zope.testing-4.1.3
```

**Comment by ihodes** [comment]
Thanks for attaching that—weird! @tavinathanson @iskandr what do you two think about this? (Asking as it looks like it's pysensembl pulling in BioPython?

**Comment by tavinathanson** [comment]
Weird!

I'm not clear why this fix would work, though, since `pyensembl` requires numpy >= 1.7 (see https://github.com/hammerlab/pyensembl/blob/master/setup.py)

**Comment by armish** [comment]
Hmm, do you think the order of the packages in the `requirement.txt` matters? Maybe an earlier version of `numpy` suffices to meet `biopython`'s dependency and then the `pyensembl` pulls a newer version in. I am saying this, because looks like within the virtualenv, I do have a newer version of `numpy`:

```
(env) $ pip list |grep "numpy\|ensembl"
numpy (1.9.2)
pyensembl (0.5.13)
```

Maybe it makes sense to bump the numpy version to 1.7 instead of 1.6.2.

**Comment by tavinathanson** [comment]
I thought install order of `requirements.txt` lines was unspecified, though having trouble finding a definitive answer and haven't tested it. https://github.com/pypa/pip/blob/d85ceb06fe3bc45dc2ca02ee6dac80ab79c2ba8e/tests/unit/test_req.py#L248 might indicate otherwise?

Since you have a newer version of `numpy` and your log says that it "Successfully installed" `numpy`, it does seem like the wonkiness is coming from `biopython`.

Do you see this issue when you just do a pip install of `biopython` in an empty virtualenv?

Another note: I haven't been able to reproduce this on my machine, using: `pip 1.5.6` in a clean virtualenv

**Comment by armish** [comment]
It might be because of my relatively old and vanilla configuration on 10.7.5:

```
(venv) $ pip --version
pip 7.0.1 from /Users/aksoyb/Projects/cycledash/venv/lib/python2.7/site-packages (python 2.7)
```

I just tried starting over with a clean virtualenv; I still get the same exact error, but seems like the installing requirements step succeeded despite the error shown and I could see that the numpy 1.9.2 was installed after the process ended.

Maybe it makes sense to close this issue for now and visit it if it really breaks the build.

**Pull request closed without merging**
