### PR TITLE
Add project_name to vcfs & enable filtering by it

### LINKED ISSUE #449: Group runs into projects
There are a lot of runs on the runs page now and linking them to a project or analysis would be useful, so we can filter the runs to a certain project.  Or folders/project structure would be nice as well.

### PR DESCRIPTION
**Pull request by ihodes**
This involved rewriting the /runs page in React.

Will need alter the DB to add project_name TEXT to the vcfs table.

fixes #449 

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/450)

### CODE REVIEW

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/450)



---

Do we not want project_name as a column in the /runs page?

---

**Comment by tavinathanson** [comment]
(Doh, I didn't mean to hit publish yet.)

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/450)



---

Doh, I didn't think it would publish that line.

---

<sup>**[cycledash/static/js/runs.js, line 10 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiHwgMrr_9_ye-t2GPQ)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L10)):</sup>
#nofilter

---

<sup>**[cycledash/static/js/runs.js, line 15 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiHy4t77zxIUcQVRyVa)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L15)):</sup>
As someone new to this runs code, the `runKeyVals`/`run_kvs` naming was pretty confusing to me. It took me a while to figure out *which* key/values this was. (And even long to realize that you meant the values of the keys, rather than key/value pairs.) Thoughts on a better variable name?  runPropertyNames? runKeyDescriptions?

---

<sup>**[cycledash/static/js/runs.js, line 38 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI1TtIXESNm_qkCp6B)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L38)):</sup>
Some of this logic feels like it could be better pushed down into the components. What if RowValues belonged to RunRow, RunRow took an isSelected property and only displayed its RowValues if isSelected === True? Or something to that effect?

---

<sup>**[cycledash/static/js/runs.js, line 92 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI0b-t3aLkqso37P_2)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L92)):</sup>
Again about naming: a values class with a key/values variable doesn't seem very descriptive. How about RowDescription and runKeyDescriptions? Or something like that?

---

<sup>**[cycledash/static/js/runs.js, line 118 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI0LRxKYsMV9fheAwP)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L118)):</sup>
How about `RunLabels`, `RunComments`, etc. to clarify that these belong to a run instead of an abstract row? (I happened to be confused by `RowComments`, thinking it was some sort of row of comments.

---

<sup>**[cycledash/static/js/runs.js, line 142 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI-lHs-RfWhS8sqxH_)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L142)):</sup>
Weird that seemingly nothing changed, but the comment bubble is now closer to the comment number than before?

---

<sup>**[cycledash/static/js/runs.js, line 152 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiHwZCs-5ObGOv2Sc4z)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L152)):</sup>
Should these just be separate files?

---

<sup>**[cycledash/templates/runs.html, line 28 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI-0epTLfhIX_DqpMv)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/templates/runs.html#L28)):</sup>
Nit: space after `tojson`?

---

**Comment by tavinathanson** [comment]
Looks good! A few minor comments.

**Comment by ihodes** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/450)



---

> Do we not want project_name as a column in the /runs page?

Not sure--more than happy to do it. It's getting crowded there, so if so, I'd like to replace something we currently have there with it. Maybe we can deploy this and see how it goes and make a quick fix if people want it?

---

<sup>**[cycledash/static/js/runs.js, line 15 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiHy4t77zxIUcQVRyVa)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L15)):</sup>
Yeah, good idea. I'm going to go with runDescriptionTitleKeys—sound reasonable? Since it's a map of titles to keys for the description.

---

<sup>**[cycledash/static/js/runs.js, line 38 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI1TtIXESNm_qkCp6B)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L38)):</sup>
That could work too. I don't necessarily think it's better that way, as you're simply pushing state further down. More importantly, though, a RunRow can't return two <tr>s; it'd need to wrap them in something like a <div>, which would break the layout of a table. Maybe there's a way around this?

---

<sup>**[cycledash/static/js/runs.js, line 142 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI-lHs-RfWhS8sqxH_)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L142)):</sup>
Hah, I didn't notice that. 

---

<sup>**[cycledash/static/js/runs.js, line 152 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiHwZCs-5ObGOv2Sc4z)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L152)):</sup>
Maybe?  I figure they should all be moved to React, but didn't want to do it all at once since it's such a discrete part. The file with comments and whitespace is <300 lines, so seems okay for now?

---

**Comment by tavinathanson** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/450)







---

<sup>**[cycledash/static/js/runs.js, line 49 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/450#-JiI1TtIXESNm_qkCp6B)** ([raw file](https://github.com/hammerlab/cycledash/blob/62b4a1ae62678246510906f667f1cbfd0794ecba/cycledash/static/js/runs.js#L49)):</sup>
Yeah, I remember running into that with `VCFRecord`. Didn't figure out a way around the table layout issue.

---

**Pull request merged**
