### PR TITLE
Fix ordering by position

### PR DESCRIPTION
**Pull request by ihodes**
Position was no longer being sorted by correctly, due to casting its type
to a string.

As noted by @arahuja in issue #407

This does not fix the issue, though; that requires a more complex sort
by contig (in the works).

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/433)

### CODE REVIEW

**Comment by ihodes** [comment]
This is failing because of the pylint requirement (don't know why) which is fixed in #434. Good to merge?

**Comment by danvk** [comment]
LGTM

**Comment by danvk** [comment]
Does this (or the previous PR) affect any screenshots?

**Comment by ihodes** [comment]
The other one ended up changing a screenshot; I've added it here.

**Pull request merged**
