### PR TITLE
Added steps to make sure the build system behaves well

### PR DESCRIPTION
**Pull request by armish**
- due to a conflict with the default postgres settings, `PGHOST` has to be set to `localhost` on a Lion before setting the database up.
- running gulp before installing the dependencies fails

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/657)

### CODE REVIEW

**Comment by ihodes** [comment]
Thanks for the PR(s)! And welcome to Cycledash :) 

Is this PGHOST issue Mountain-Lion specific? I'm not sure I entirely understand what the issue is.

In step 2 we do note that you must `npm install` (cf. https://github.com/hammerlab/cycledash/pull/657/files#diff-4094cb644c5de856901e1e5ea3da2a16L30) :)

**Comment by armish** [comment]
yeah, it might be Lion-specific. I was getting this error when trying to connect to the database:

```
$ createdb cycledash
createdb: could not connect to database postgres: could not connect to server: Permission denied
	Is the server running locally and accepting
	connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"?
```

and turns out people have already [figured how to resolve this issue](http://stackoverflow.com/questions/13868730/socket-file-var-pgsql-socket-s-pgsql-5432-missing-in-mountain-lion-os-x-ser) on Lion.

Sorry for missing the `npm install` part earlier.

**Comment by ihodes** [comment]
Huh, interesting. I'd lean towards leaving this out of `DEVELOP.md`, as it may be specific to a particular way of installing Postgres on a particular OS? (Are you running Mountain Lion)? @jaclynperrone did you run into this when you were setting up Cycledash recently?

**Comment by armish** [comment]
Unfortunately yes: my temporary workstation is running `10.7.5` and I agree to leave this out if this is really an old version specific issue. Thanks @ihodes!

**Comment by ihodes** [comment]
No worries—thanks for looking into this! Let's hold off on this PR then until we try it out with a new workstation soon.

**Pull request closed without merging**
