### PR TITLE
Remove UNIQUE constraint on VCF URIs

### PR DESCRIPTION
**Pull request by ihodes**
Adds one on (uri, project_id)

(Changes already made to DB on server.)

Migration SQL:

``` sql
drop INDEX vcf_uri_key;
create unique index concurrently vcfs_project_id_uri_key on vcfs (project_id, uri);
```

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/795)

### CODE REVIEW

**Comment by danvk** [comment]
Wasn't there another change in your hotfix? (i.e. making caller name optional)

**Comment by ihodes** [comment]
That was already deployed, but wasn't reflected in the production Postgres DB.

**Comment by armish** [comment]
LTGM -- are you planning to get the change @danvk mentioned in this request or planning on a new PR for that?

**Comment by armish** [comment]
never mind my question, was too slow to post it ;)

**Comment by ihodes** [comment]
:cycle: :dash:

**Comment by danvk** [comment]
Got it. @armish maybe it's time for you to do your first cycledash deploy! :) It would be nice to get track names, loading indicators and the coverage track deployed.

**Comment by armish** [comment]
sure -- I will love to do that. @ihodes, given that you already updated the schema on the server, that will require only a code update, right?

**Comment by ihodes** [comment]
On Thu, Jul 23, 2015 at 12:09 PM, B. Arman Aksoy <notifications@github.com>
wrote:

> sure -- I will love to do that. @ihodes <https://github.com/ihodes>,
> given that you already updated the schema on the server, that will require
> only a code update, right?
>
>
Yessir. (Assuming there haven't been other schema updates since the last
deploy… :\ https://github.com/hammerlab/cycledash/issues/776)

**Comment by ihodes** [comment]
Tests passed (aside from seltest, which is removed from travis test script in @jaclynperrone's PR). Good to merge?

**Comment by armish** [comment]
:+1: for the merge

**Comment by armish** [comment]
Coveralls is taking things sloooooow, I guess :\

**Comment by ihodes** [comment]
Looks like it's not working? Last PR merged in also didn't have a completing Coveralls. Will file an issue to fix it and merge this in.

**Pull request merged**
