### PR TITLE
Issue 621 Use Voluptuous for object marshaling + object documentation

### LINKED ISSUE #621: Use voluptuous for marshal_with in the Python API
Migrate to use voluptuous for marshal_with, and **add docstring** to each field in the request/response schemas. These can later be used to generate documentation.

### PR DESCRIPTION
**Pull request by ihodes**
Use Voluptuous for object marshaling, and add object documentation
directly to those validation objects.

This will let us programmatically extract API documentation directly from
the code. Additionally, we get to use the same EDSL for validation and
marshaling objects.

Fixes #621

Migration:

``` sql
alter table vcfs drop column validation_vcf;
alter table vcfs drop column f1score;
alter table vcfs drop column recall;
alter table vcfs drop column precision;
```

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/786)

### CODE REVIEW

**Comment by danvk** [comment]
Reviewed 5 of 11 files at r1.
Review status: 5 of 11 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/__init__.py, line 26 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8IGJhJDw2nqw3gG9y)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/__init__.py#L26)):</sup>
`code` → `status_code`

---

<sup>**[cycledash/__init__.py, line 28 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8I97Gnro-CphoCXBA)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/__init__.py#L28)):</sup>
Don't we want to send minified JSON over the wire?

---

<sup>**[cycledash/api/__init__.py, line 62 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8IeTQr2r35URDHLI1)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/__init__.py#L62)):</sup>
this link should include a SHA so that it doesn't rot

---

<sup>**[cycledash/api/__init__.py, line 71 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8ItwDsiKu8HnXb4fm)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/__init__.py#L71)):</sup>
move this out of the `if`/`elif` since it's identical in each case

---

<sup>**[cycledash/api/__init__.py, line 75 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8J1Tzah4K-eigMOpI)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/__init__.py#L75)):</sup>
The docstring says it should be a dict, list or object.

---

<sup>**[cycledash/api/__init__.py, line 87 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8JaRhAVlqvX-MkDEO)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/__init__.py#L87)):</sup>
It's a little confusing that `resp` changes type here. Why not just use a different var?

---

<sup>**[cycledash/api/__init__.py, line 91 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8JWoAkYePnaRw8OT5)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/__init__.py#L91)):</sup>
How about consolidating by doing concatenating to the returned tuple?

```python
resp, status = resp[:2]
resp = marshal(resp, schema, envelope=envelope)
resp = camelcase_dict(resp)
headers = () if len(resp) == 2 else (resp[2],)
return (resp, status) + headers
```

---

<sup>**[cycledash/api/comments.py, line 62 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8KlGmEjPiUBeUDO-f)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/comments.py#L62)):</sup>
Didn't like `EpochField` any more? Did it not work with `Doc`?

---

<sup>**[cycledash/api/tasks.py, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LLBHOEZJ_da3H5zA)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/tasks.py#L18)):</sup>
Can you make the enum explicit in the Schema? (e.g. `OneOf('a', 'b', 'c', ...)`)

---

<sup>**[cycledash/helpers.py, line 2 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LWK3Q2rOUMX5apoo)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/helpers.py#L2)):</sup>
Don't think you need this

---

<sup>**[schema.sql, line 40 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LfXSjuFexTj4PeUx)** ([raw file](https://github.com/hammerlab/cycledash/blob/1d2acef9151e7e8ea74638cf183f48c501bb4194/schema.sql#L40)):</sup>
Is this related to the documentation change, or just cleanup?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/786)

**Comment by ihodes** [comment]
Review status: 2 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[cycledash/api/__init__.py, line 91 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8JWoAkYePnaRw8OT5)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/__init__.py#L91)):</sup>
Yeah this can definitely be tightened up—I tried something else :)

---

<sup>**[cycledash/api/comments.py, line 62 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8KlGmEjPiUBeUDO-f)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/comments.py#L62)):</sup>
EpochField worked with flask-restful's fields—it's not part of voluptuous though, so this now works with voluptuous. Does the same thing, though.

---

<sup>**[cycledash/api/tasks.py, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LLBHOEZJ_da3H5zA)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/tasks.py#L18)):</sup>
I'm all for that—I asked about that (adding an enum in the DB schema) in the PR that introduced Tasks, but IIRC we didn't want to go that route for some reason?  So, I just went the route of following the database DB when creating this schema. Think I should file an issue to document the possible states?

---

<sup>**[cycledash/helpers.py, line 2 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LWK3Q2rOUMX5apoo)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/helpers.py#L2)):</sup>
Good catch, surprised pylint didn't catch it.

---

<sup>**[schema.sql, line 40 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LfXSjuFexTj4PeUx)** ([raw file](https://github.com/hammerlab/cycledash/blob/1d2acef9151e7e8ea74638cf183f48c501bb4194/schema.sql#L40)):</sup>
Just cleanup—overdue. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/786)

**Comment by danvk** [comment]
Looks good. The screenshot tests are failing on Travis. It's not clear to me why this PR would affect them, though.

---

Review status: 2 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/api/__init__.py, line 41 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-JuBypGrh8xYMKCK8ASY)** ([raw file](https://github.com/hammerlab/cycledash/blob/3df059cb4c1e6f03cf7167d81d2c60854990e3f2/cycledash/api/__init__.py#L41)):</sup>
nit: information about the specific types that an argument can take on makes more sense in the docs for that argument. The first line should just be a high-level description, like `Filter data using a voluptuous Schema`.

---

<sup>**[cycledash/api/__init__.py, line 42 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-JuBzI9cqN_at88Grf75)** ([raw file](https://github.com/hammerlab/cycledash/blob/3df059cb4c1e6f03cf7167d81d2c60854990e3f2/cycledash/api/__init__.py#L42)):</sup>
`Schema` (sp)

---

<sup>**[cycledash/api/tasks.py, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LLBHOEZJ_da3H5zA)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/tasks.py#L18)):</sup>
Sure, sounds good.

---

<sup>**[cycledash/helpers.py, line 2 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LWK3Q2rOUMX5apoo)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/helpers.py#L2)):</sup>
It was the only addition to this file, so it was easy to spot. We run pylint with `--errors-only`, so it makes sense that we miss this sort of thing. Our JS linting for Cycledash is stricter.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/786)

**Comment by ihodes** [comment]
Thanks for the review! 

For posterity, screenshots failing due to earlier change that no longer hid comment time; this is fixed in the following commit.

---

Review status: 2 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[cycledash/api/__init__.py, line 41 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-JuBypGrh8xYMKCK8ASY)** ([raw file](https://github.com/hammerlab/cycledash/blob/3df059cb4c1e6f03cf7167d81d2c60854990e3f2/cycledash/api/__init__.py#L41)):</sup>
Definitely, good call. A worthwhile nit!

---

<sup>**[cycledash/api/tasks.py, line 18 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/786#-Ju8LLBHOEZJ_da3H5zA)** ([raw file](https://github.com/hammerlab/cycledash/blob/30f73fee90616c3f53157f464cb616dfaf0dc516/cycledash/api/tasks.py#L18)):</sup>
Cool, filed: https://github.com/hammerlab/cycledash/issues/788

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/786)

**Pull request merged**
