### PR TITLE
Use Alembic for migrations

### LINKED ISSUE #776: Handle migrations better
Currently we list them in the notes of a PR that makes changes. This isn't great.

Something like Alembic may work.

### PR DESCRIPTION
**Pull request by ihodes**
Fixes #776 
cc @danvk 

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/cycledash/801)

### CODE REVIEW

**Comment by danvk** [comment]
I'm not too familiar with Alembic. Could you walk me through what a database migration looks like in this new world?

---

Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[alembic/env.py, line 1 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZYMlG8YBLYlhgnJfG)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/alembic/env.py#L1)):</sup>
Is this file also boilerplate that's copied from somewhere? Worth noting if so.

---

<sup>**[alembic/versions/README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZWf5X1CHn1vNOdHmq)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/alembic/versions/README.md#L1)):</sup>
Will migrations be committed? Just say "contains" then, I doubt we'll remember to update the tense once it happens :)

---

<sup>**[DEVELOP.md, line 58 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZWSk7vlITwnpkTtHj)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/DEVELOP.md#L58)):</sup>
It's not clear to me if this comment is explaining what the Python script does, or if it's something that I'm supposed to do before running this script.

---

<sup>**[DEVELOP.md, line 200 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXEw_HTGJcxRX7eHH)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/DEVELOP.md#L200)):</sup>
"a simple migration" → "a simple migration" or "simple migrations"

---

<sup>**[schema.py, line 3 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXTg73JF5hFqPxsDG)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/schema.py#L3)):</sup>
Does `import *` not also `import sql`?

---

<sup>**[scripts/init_db.py, line 43 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXpL1LzMoG-aBxk-q)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/scripts/init_db.py#L43)):</sup>
Where does this store the "stamp"?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/801)

**Comment by ihodes** [comment]
The steps are 1) Make a migration script containing the migration instructions for the change 2) Run the script using alembic. Alembic keeps track of which upgrades you've run by tracking the most recent migration's GUI in the DB (the "stamp" you ask about below). cf http://alembic.readthedocs.org/en/latest/tutorial.html#create-a-migration-script for a short concrete example.

---

Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[alembic/env.py, line 1 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZYMlG8YBLYlhgnJfG)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/alembic/env.py#L1)):</sup>
It's just a file generated by Alembic, and then modified by me to work for us, not copied. 

---

<sup>**[alembic/versions/README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZWf5X1CHn1vNOdHmq)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/alembic/versions/README.md#L1)):</sup>
Sure—honestly this can go away when we add a script here, some file was just needed here to keep the directory. I'll change it to a `.keep` file or something.

---

<sup>**[DEVELOP.md, line 58 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZWSk7vlITwnpkTtHj)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/DEVELOP.md#L58)):</sup>
I'll just remove this comment; the script itself does this check.

---

<sup>**[DEVELOP.md, line 200 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXEw_HTGJcxRX7eHH)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/DEVELOP.md#L200)):</sup>
You confused me for a second :) Fixed

---

<sup>**[schema.py, line 3 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXTg73JF5hFqPxsDG)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/schema.py#L3)):</sup>
It does not, but it does import `func`, which is all I needed from sql!

---

<sup>**[scripts/init_db.py, line 43 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXpL1LzMoG-aBxk-q)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/scripts/init_db.py#L43)):</sup>
In the database (cf. explanation above)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/801)

**Comment by danvk** [comment]
Cool, this seems relatively painless & a clear win over our current manual process.

What's the migration process from our current Alembic-less setup to the new world? Let's do a Cycledash deploy & get this in place today before we all start going on vacation.

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

<sup>**[scripts/init_db.py, line 2 \[r2\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZs6Z3qcBQXc5qQ6AW)** ([raw file](https://github.com/hammerlab/cycledash/blob/a5f3c13c05582813641dfa2c91b3d536db560f03/scripts/init_db.py#L2)):</sup>
So `necessry`! (sp)

---

<sup>**[scripts/init_db.py, line 43 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXpL1LzMoG-aBxk-q)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/scripts/init_db.py#L43)):</sup>
It's in a separate table in the DB?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/801)

**Comment by ihodes** [comment]
> What's the migration process from our current Alembic-less setup to the new world?

There is no migration process whatsoever! 

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[scripts/init_db.py, line 43 \[r1\]](https://reviewable.io:443/reviews/hammerlab/cycledash/801#-JvZXpL1LzMoG-aBxk-q)** ([raw file](https://github.com/hammerlab/cycledash/blob/b5931eeecaef131e7847abbf13e40076c6ad874a/scripts/init_db.py#L43)):</sup>
Yep, `alembic_version`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/cycledash/801)

**Pull request merged**
